import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AppWrapper } from '@/context/stepContext';
import { ConfigProvider } from 'antd';
import StoreProvider from "./StoreProvider";
import { NextUIProvider } from "@nextui-org/react";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="ss01" >

      <body>

        <NextUIProvider>
          <AntdRegistry>

            <AppWrapper>

              <ConfigProvider

                theme={{

                }}
              >
                <main className="ss01 w-full max-h-screen relative m-auto bg-white shadow flex   flex-col items-center justify-between duration-700">
                  <StoreProvider>
                    {children}
                  </StoreProvider>
                </main>

              </ConfigProvider>

            </AppWrapper>

          </AntdRegistry>
        </NextUIProvider>
      </body>

    </html>
  );
}
